espoon-voltti/espooevents-service

docker-compose.yml, local_settings.py.espooevents
=> Docker configurations

README.md
=> Add correct settings file reference

.gitignore
~~- [ ] The API's adhere to the [REST API conventions](https://voltti.atlassian.net/wiki/spaces/VOLTTI/pages/46170144/REST-rajapintak+yt+nn+t)~~
~~- [ ] Tests have been written for the change (use case, repository, REST API)~~
~~- [ ] All tests pass~~
~~- [ ] The change has been tested locally, e.g., with httpie~~
```
```
=> chore: add venv to gitignore

README.md
delete links to city of helsinki's gitter and waffle.io
~~- [ ] The API's adhere to the [REST API conventions](https://voltti.atlassian.net/wiki/spaces/VOLTTI/pages/46170144/REST-rajapintak+yt+nn+t)~~
~~- [ ] Tests have been written for the change (use case, repository, REST API)~~
~~- [ ] All tests pass~~
~~- [x] All code has been linted and there aren't any lint errors~~
~~- [ ] The change has been tested locally, e.g., with httpie~~
```
```
=> docs: delete Helsinki's links

docker/django/.dockerignore
=> fix: dockerignore local_settings

.circleci/config.yml
Initialize Circle CI configuration
```
```
=> Circle ci init

local_settings.py.espooevents
Removes "comments" that broke the program, adds closing curly brackets in the end.
```
```
=> Fix problems with local settings template

README.md
delete links to helsinki's travis, codecov and requires.io
```
```
=> chore: delete Helsinki's links

migrate.sh
=> feat: add script for running migrations and starting django server

docker-compose.yml
Get specific elasticsearch version from docker hub. This enables docker-compose to build and run the project locally for now.
-
-
```
```
=> [ES-7] get specific elasticsearch version from docker hub

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
[ES-6]
```
```
[ES-6]: https://voltti.atlassian.net/browse/ES-6
=> [ES-6]: Configure pr template and code owners

README.md
[ES-34](https://voltti.atlassian.net/browse/ES-34)
```
```
=> [ES-34] JWT Documentation

.circleci/config.yml, .dockerignore, .editorconfig, Dockerfile.dist, Makefile, bin/git-hooks.sh, entrypoint.dist.sh, entrypoint.importer.sh
[ES-86]
```
```
[ES-86]: https://voltti.atlassian.net/browse/ES-86
=> [ES-86]: Configure Docker for batch jobs

.circleci/config.yml, Makefile, bin/test_ci.sh, docker-compose.yml, docker/django/docker-entrypoint.sh, docker/postgres/docker-entrypoint.sh, entrypoint.admin.sh, entrypoint.dist.sh, linkedevents/settings.py, linkedevents/test.py, requirements.in, requirements.txt
Configure Redis for session storage so that we can make the espooevents-service backend stateless. This allows us to run multiple instances of the backend for better fault tolerance.
[ES-128]
```
```
[ES-128]: https://voltti.atlassian.net/browse/ES-128
=> [ES-128]: Configure Redis for session storage

.circleci/config.yml
[ES-163]
The latest builder-aws Docker image has Terraform 0.12.23 installed.
```
```
[ES-163]: https://voltti.atlassian.net/browse/ES-163
=> [ES-163]: Upgrade builder-aws Docker image to latest version

.circleci/config.yml
[ES-201]
```
```
[ES-201]: https://voltti.atlassian.net/browse/ES-201
=> [ES-201]: Fix jq problems by caching jq

.circleci/config.yml, .dockerignore, Dockerfile.dist, Makefile, bin/test_ci.sh, docker/django/Dockerfile, docker/django/docker-entrypoint.sh
- Optimize Docker layer ordering for better cache use. This speeds up the CI workflows.
[ES-195]
```
```
[ES-195]: https://voltti.atlassian.net/browse/ES-195
=> [ES-195]: Refactor Docker

Makefile
Add examples for running update_n_events for keywords and places.
[ES-208]
```
```
[ES-208]: https://voltti.atlassian.net/browse/ES-208
=> [ES-208]: Add examples for running update_n_events

events/management/commands/add_helsinki_topics.py
Add remote participation keyword to helsinki topics since this keyword is automatically added when the event location is set to Internet in espooevents-frontend.
[ES-289]
```
```
[ES-289]: https://voltti.atlassian.net/browse/ES-289
=> [ES-289]: Add remote participation keyword to helsinki topics

Makefile
**Fixed**
- Fix Makefile's lint command by adding missing environment variable
- Fix importers by adding missing environment variable
[ES-345]
None.
```
```
[ES-345]: https://voltti.atlassian.net/browse/ES-345
=> [ES-345]: Fix make commands

Dockerfile.dist
=> Fix docker build of Dockerfile.dist

events/management/commands/add_espoo_places.py
See https://github.com/espoon-voltti/espooevents-frontend/pull/104
=> fix(keywords): sync postal-code to keyword map with frontend

events/api.py, events/tests/conftest.py, events/tests/test_event_get.py
Use the `date_published` field to support timed publication. Events with `date_published` in the future are filtered out from event listings for unauthenticated users and users of other organizations than the publisher.
```
```
=> Timed publication of events

bin/test_ci.sh
=> Fail the CI run if tests fail

events/api.py
=> Return recently published events with the last_modified_since query

.circleci/config.yml, entrypoint.dist.sh
=> chore(ci): remove dev environment

.dockerignore, Dockerfile.dist, Makefile, events/management/commands/add_espoo_topics.py
also fix lint warning in add_espoo_topics.py
=> fix: relocate quickfix to be included in image

Dockerfile.dist, entrypoint.dist.sh
- Add support for running the service container in Fargate environment.
=> VP:746: Add support for running the service container in Fargate environment.

.github/workflows/build.yml
=> Use Github Actions OIDC provider

.github/workflows/build.yml
=> fix(ci): remove removed environment

events/management/commands/add_espoo_audience.py
=> add jobseekers audience

Makefile
Added migration commands to the makefile:
- make make_migrations runs the makemigration command in the docker container
- make migrate runs the migrate command in the docker container
```
```
=> Added migration commands to makefile

linkedevents/settings.py
- Django no longer appends missing slashes
=> fix : set APPEND_SLASH to False

events/api.py
- Some logging has been added to `update` methods
=> chore: add logging to update methods

events/api.py
Added more logging to bulk update
=> chore: add bulk update logging

events/api.py
Add more logging to validations
=> Add more logging to validations

events/api.py
Figuring out the issue
```
```
=> add logging

events/api.py
Poistettu vanhoja lokeja, ja lisätty uusia.
```
```
=> add logs and remove old logs

events/api.py
=> change logging

events/api.py
=> add formatting

events/api.py
Poistettu kaikki lisätyt lokitukset
Oon testannut tätä `git diff b27ee74..HEAD`.
```
```
=> revert logs

events/api.py
- One comparison has been made faster which results in bulk update being considerably faster
=> Fix: bulk update timeout

events/fixtures/hobby_categories.json
- two new hobby-categories have been to fixtures
=> chore: add two more hobby categories to fixtures

events/api.py, events/tests/test_event_put.py
- The `FORM_ERRORS` format has been changed so that the frontend can handle  and show tooltips in the form.
=> chore: improve error handling
